### ISSUE TITLE
Error mirroring bitbucket

### ISSUE THREAD

**Issue by lu-zero** [felipec/git-remote-hg#18]
Here the configuration in use
```
[remote "github"]
        url = git@github.com:lu-zero/moin-2.0.git
        fetch = +refs/heads/*:refs/remotes/github/*
[remote "origin"]
        url = hg::https://bitbucket.org/thomaswaldmann/moin-2.0
        fetch = +refs/heads/*:refs/remotes/origin/*
        pushurl = git@github.com:lu-zero/moin-2.0.git
[branch "master"]
        remote = origin
        merge = refs/heads/branches/default
```
Here the message
```
~/mirror/moin-2.0(master) $ git pull; git push                                                                                               
searching for changes
adding changesets
adding manifests
adding file changes
added 629 changesets with 1690 changes to 419 files
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python-exec/python2.7/git-remote-hg", line 1293, in main
    marks = Marks(marks_path, repo)
  File "/usr/lib/python-exec/python2.7/git-remote-hg", line 119, in __init__
    self.load()
  File "/usr/lib/python-exec/python2.7/git-remote-hg", line 142, in load
    tmp = json.load(open(self.path))
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by felipec** [comment]
Yes, looks like the marks file got corrupted. Perhaps you can run `git-marks-check`:

**Comment by lu-zero** [comment]
I will do that soon, thanks a lot!
