### ISSUE TITLE
Push to bitbucket not working with latest git-remote-hg

### ISSUE THREAD

**Issue by Ormod** [felipec/git-remote-hg#21]
I have Git version 1.8.5, Mercurial 3.1.1 and latest git-remote-hg git revision, and when trying to push, I get this:

Traceback (most recent call last):
  File "/usr/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/git-remote-hg", line 1308, in main
    do_export(parser)
  File "/usr/bin/git-remote-hg", line 1185, in do_export
    if not push(parser.repo, peer, parsed_refs, p_revs):
  File "/usr/bin/git-remote-hg", line 1073, in push
    ret = push_unsafe(repo, remote, parsed_refs, p_revs)
  File "/usr/bin/git-remote-hg", line 1048, in push_unsafe
    ret = remote.unbundle(cg, remoteheads, 'push')
  File "/Library/Python/2.7/site-packages/mercurial-3.1.1-py2.7-macosx-10.9-intel.egg/mercurial/wireproto.py", line 395, in unbundle
    stream = self._calltwowaystream('unbundle', cg, heads=heads)
  File "/Library/Python/2.7/site-packages/mercurial-3.1.1-py2.7-macosx-10.9-intel.egg/mercurial/httppeer.py", line 222, in _calltwowaystream
    d = fp.read(4096)
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by felipec** [comment]
It seems to be working here. Please test with the latest version (v0.4).
