### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by simonzack** [felipec/git-remote-hg#29]
I'm encountering an error while cloning pywin32 on cygwin. The hg repository clones fine. Versions: git 2.1.1, mercurial 3.0.1 (these are the latest on cygwin).

```
$ git clone hg::http://pywin32.hg.sourceforge.net/hgweb/pywin32/pywin32/
Cloning into 'pywin32'...
real URL is http://pywin32.hg.sourceforge.net:8000/hgroot/pywin32/pywin32/
requesting all changes
adding changesets
adding manifests
adding file changes
added 4354 changesets with 10537 changes to 1961 files
progress revision 99 'master' (100/4106)
progress revision 199 'master' (200/4106)
progress revision 299 'master' (300/4106)
progress revision 399 'master' (400/4106)
progress revision 499 'master' (500/4106)
progress revision 599 'master' (600/4106)
progress revision 699 'master' (700/4106)
progress revision 799 'master' (800/4106)
progress revision 899 'master' (900/4106)
progress revision 999 'master' (1000/4106)
progress revision 1099 'master' (1100/4106)
progress revision 1199 'master' (1200/4106)
progress revision 1299 'master' (1300/4106)
progress revision 1399 'master' (1400/4106)
progress revision 1499 'master' (1500/4106)
progress revision 1599 'master' (1600/4106)
progress revision 1699 'master' (1700/4106)
error: git-fast-import died of signal 11
fatal: Error while running fast-import
$ Traceback (most recent call last):                                                                                                                                                                                                   128 ↵
  File "/usr/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/git-remote-hg", line 1306, in main
    do_import(parser)
  File "/usr/bin/git-remote-hg", line 718, in do_import
    export_head(repo)
  File "/usr/bin/git-remote-hg", line 616, in export_head
    export_ref(repo, g_head[0], 'bookmarks', g_head[1])
  File "/usr/bin/git-remote-hg", line 547, in export_ref
    modified_final = export_files(c.filectx(f) for f in modified)
  File "/usr/bin/git-remote-hg", line 276, in export_files
    fid = node.hex(f.filenode())
  File "/usr/lib/python2.7/site-packages/mercurial/context.py", line 528, in filenode
    return self._filenode
  File "/usr/lib/python2.7/site-packages/mercurial/util.py", line 287, in __get__
    result = self.func(obj)
  File "/usr/lib/python2.7/site-packages/mercurial/context.py", line 483, in _filenode
    return self._filelog.lookup(self._fileid)
  File "/usr/lib/python2.7/site-packages/mercurial/revlog.py", line 840, in lookup
    raise LookupError(id, self.indexfile, _('no match found'))
mercurial.error.LookupError: data/com/win32com/util.py.i@0c5f158ba9cd: no match found
close failed in file object destructor:
sys.excepthook is missing
```

**Comment by fingolfin** [comment]
@mcepl Why exactly do you think this is the same issue? There are two different errors, with different backtraces, on different repositories, with different version of git and hg...

**Comment by mcepl** [comment]
Yes, sorry ... it was too late.

**Comment by CedricGatay** [comment]
I am facing the same kind of issue (no match found while importing), is there any workaround for importing ?

**Comment by fingolfin** [comment]
@simonzack Does this still occur for you? I cannot reproduce it on Mac OS X 10.11, with git 2.6.3, hg 3.6.1, and my fork of git-remote-hg, i.e. https://github.com/fingolfin/git-remote-hg/

**Comment by alexei-31** [comment]
@simonzack: I has no prombem to clone it on Windows XP SP3 with git 2.6.3, hg 3.6.1 and git-remote-hg from @fingolfin fork https://github.com/fingolfin/git-remote-hg/
![screenshot of cloning pywin32.hg.sourceforge.net](https://bitbucket.org/Alexei_31/test5/downloads/pywin32.hg.sourceforge.net.png)

**Comment by felipec** [comment]
This should be solved in the latest versions, right?
