### ISSUE TITLE
bad operand type when pushing.

### ISSUE THREAD

**Issue by urkle** [felipec/git-remote-hg#31]
I cloned a Mecurial repository via the latest version of this script.. and upon pushing came up with this stack trace.

```python
Traceback (most recent call last):
  File "/Users/urkle/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/Users/urkle/bin/git-remote-hg", line 1308, in main
    do_export(parser)
  File "/Users/urkle/bin/git-remote-hg", line 1185, in do_export
    if not push(parser.repo, peer, parsed_refs, p_revs):
  File "/Users/urkle/bin/git-remote-hg", line 1073, in push
    ret = push_unsafe(repo, remote, parsed_refs, p_revs)
  File "/Users/urkle/bin/git-remote-hg", line 1036, in push_unsafe
    if not checkheads(repo, remote, p_revs):
  File "/Users/urkle/bin/git-remote-hg", line 1005, in checkheads
    ancestors = repo.changelog.ancestors([rev], stoprev=min(old))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mercurial/revlog.py", line 369, in ancestors
    inclusive=inclusive)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mercurial/ancestor.py", line 242, in __init__
    self._containsvisit = [-rev for rev in revs]
TypeError: bad operand type for unary -: 'NoneType'
```

I'm using Mecurial 3.1 on python 2.7.8 (mac ports)

**Comment by felipec** [comment]
Ok. If you find a way to reproduce the issue please reopen.
