### ISSUE TITLE
"AttributeError: 'localrepository' object has no attribute 'pull'" with hg 3.2.4 on Mac OS 10.10

### ISSUE THREAD

**Issue by dmolesUC3** [felipec/git-remote-hg#34]
When I try to clone my hg repo (which works with hg), I get:
```
Cloning into 'my-repo'...
Traceback (most recent call last):
  File "/Users/dmoles/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/Users/dmoles/bin/git-remote-hg", line 1286, in main
    repo = get_repo(url, alias)
  File "/Users/dmoles/bin/git-remote-hg", line 433, in get_repo
    repo.pull(peer, heads=None, force=True)
  File "/Library/Python/2.7/site-packages/mercurial/repoview.py", line 307, in __getattr__
    return getattr(self._unfilteredrepo, attr)
AttributeError: 'localrepository' object has no attribute 'pull'
```
My hg version is 3.2.4+20150107, and my git version is 1.9.3 (Apple Git-50). I'm using revision 3cb0da9 of git-remote-hg.

**Comment by dmolesUC3** [comment]
Sorry, this was a duplicate of #27 .
