### ISSUE TITLE
KeyError: '0000000000000000000000000000000000000000'

### ISSUE THREAD

**Issue by tarsius** [felipec/git-remote-hg#47]
I get the following error when trying to clone `ssh://hg@bitbucket.org/lyro/evil`. Do you have an idea why that might be happening? Thanks for your help!

```
Cloning into 'evil'...
requesting all changes
adding changesets
adding manifests
adding file changes
added 1697 changesets with 3546 changes to 51 files (+1 heads)
progress revision 0 'master' (0/1697)
progress revision 100 'master' (100/1697)
...
progress revision 1600 'master' (1600/1697)
Traceback (most recent call last):
  File "/home/jonas/bin/git-remote-hg", line 1246, in <module>
    sys.exit(main(sys.argv))
  File "/home/jonas/bin/git-remote-hg", line 1228, in main
    do_import(parser)
  File "/home/jonas/bin/git-remote-hg", line 679, in do_import
    export_bookmark(repo, bmark)
  File "/home/jonas/bin/git-remote-hg", line 566, in export_bookmark
    export_ref(repo, bmark, 'bookmarks', head)
  File "/home/jonas/bin/git-remote-hg", line 531, in export_ref
    print "from :%u" % rev_to_mark(head)
  File "/home/jonas/bin/git-remote-hg", line 432, in rev_to_mark
    return marks.from_rev(rev.hex())
  File "/home/jonas/bin/git-remote-hg", line 168, in from_rev
    return self.marks[rev]
KeyError: '0000000000000000000000000000000000000000'
fatal: stream ends early
fast-import: dumping crash report to /tmp/evil/.git/fast_import_crash_14506
fatal: Error while running fast-import
```

**Comment by fingolfin** [comment]
I can't reproduce this with [my fork of git-remote-hg](https://github.com/fingolfin/git-remote-hg), git 2.6.3 and Mercurial 3.6.1.

What versions of git and mercurial are you using? Can you perhaps try it with my fork, too?

**Comment by tarsius** [comment]
I though I had recently updated `git-remote-hg` but it turns out I was still using an old version. After updating to (Felipe's) last version I am able to clone that repository and also get a hint about why the old version (probably) failed:

```
WARNING: Ignoring invalid bookmark 'bs-digraph'
WARNING: Ignoring invalid bookmark 'lyro-doc'
```

Sorry for the noise.
