### ISSUE TITLE
httplib.IncompleteRead: IncompleteRead(31 bytes read)

### ISSUE THREAD

**Issue by kenorb** [felipec/git-remote-hg#50]
The following error happened while cloning one repo:

```
Cloning into 'repos/2013-2-1172-aa-tree'...
Traceback (most recent call last):
  File "/home/kenorb/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/home/kenorb/bin/git-remote-hg", line 1286, in main
    repo = get_repo(url, alias)
  File "/home/kenorb/bin/git-remote-hg", line 433, in get_repo
    repo.pull(peer, heads=None, force=True)
  File "/usr/lib/python2.7/dist-packages/mercurial/localrepo.py", line 1545, in pull
    force=force)
  File "/usr/lib/python2.7/dist-packages/mercurial/discovery.py", line 45, in findcommonincoming
    abortwhenunrelated=not force)
  File "/usr/lib/python2.7/dist-packages/mercurial/setdiscovery.py", line 109, in findcommonheads
    batch.submit()
  File "/usr/lib/python2.7/dist-packages/mercurial/wireproto.py", line 76, in submit
    self._submitreq(req, rsp)
  File "/usr/lib/python2.7/dist-packages/mercurial/wireproto.py", line 78, in _submitreq
    encresults = self.remote._submitbatch(req)
  File "/usr/lib/python2.7/dist-packages/mercurial/wireproto.py", line 160, in _submitbatch
    rsp = self._call("batch", cmds=';'.join(cmds))
  File "/usr/lib/python2.7/dist-packages/mercurial/httprepo.py", line 171, in _call
    return fp.read()
  File "/usr/lib/python2.7/dist-packages/mercurial/keepalive.py", line 425, in read
    s = self._rbuf + self._raw_read(amt)
  File "/usr/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/dist-packages/mercurial/keepalive.py", line 448, in _read_chunked
    raise httplib.IncompleteRead(value)
httplib.IncompleteRead: IncompleteRead(31 bytes read)
```

This happened for this one:

```
git clone "hg::https://code.google.com/p/2013-2-1172-aa-tree/"
```

but I can't reproduce it after second try, so not sure if there is anything to fix.

**Comment by alexei-31** [comment]
Please, try repeat this problem in git-remote-hg fork, see https://github.com/fingolfin/git-remote-hg
I was check it on my computer and has no problem.

**Comment by felipec** [comment]
I supposed this didn't happen again.
