### ISSUE TITLE
fatal: mark :76404 not declared

### ISSUE THREAD

**Issue by tenpn** [felipec/git-remote-hg#65]
I've been using git-remote-hg happily for months. However today, without having updated git or git-remote-hg, I'm unable to push or fetch or pull. Instead I get this error:

```
11:55 am % git fetch
searching for changes
no changes found
fatal: mark :76404 not declared
fast-import: dumping crash report to .git/fast_import_crash_54458
fatal: Error while running fast-import
Traceback (most recent call last):
  File "/Users/Andrew/bin//git-remote-hg", line 1356, in <module>
    sys.exit(main(sys.argv))
  File "/Users/Andrew/bin//git-remote-hg", line 1340, in main
    do_import(parser)
  File "/Users/Andrew/bin//git-remote-hg", line 739, in do_import
    export_branch(repo, branch)
  File "/Users/Andrew/bin//git-remote-hg", line 631, in export_branch
    export_ref(repo, branch, 'branches', head)
  File "/Users/Andrew/bin//git-remote-hg", line 611, in export_ref
    print "N inline :%u" % rev_to_mark(c)
IOError: [Errno 32] Broken pipe
```

Here's a gist with the crash dump mentioned above: https://gist.github.com/tenpn/a5bedf7680797d5657919feee5fd938a

I've updated git-remote-hg to see if that helps, and it doesn't. 

Is that mark :9999 something to do with my project? Is there possibly some issue with either the remote hg or the local git repo? Or is it a bug with git-remote-hg?

**Comment by tenpn** [comment]
Found this earlier issue, which resolve it: https://github.com/felipec/git-remote-hg/issues/4
