### ISSUE TITLE
Pushed commits do not actually wind up on remote

### ISSUE THREAD

**Issue by jdagilliland** [felipec/git-remote-hg#67]
I'm cloning a local hg repo, and having issues actually getting my git commits back to this hg repo. Maybe I'm missing something, but this is a test case of what is going on.

```
-> % cd ~/tmp/remote-hg-test/
-> % git clone "hg::$HOME/tmp/remote-hg-test/hg-repo" git-repo
Cloning into 'git-repo'...
Checking connectivity... done
-> % cd git-repo 
-> % git log | cat
commit f0060fedf04cf334398d1db7ef9655a482221298
Author: Jason Gilliland <redacted@redacted.com>
Date:   Tue Jan 3 13:50:33 2017 -0500

    Started file

-> % cat file                                                                                                                                                                        
This is my file short and stout
-> % echo "Now shorter and stouter" >> file 
-> % git add file
-> % git commit
-> % git log | cat
commit 4aa00fe7190f656462e10dea048fabb87a60f643
Author: Jason Gilliland <redacted@redacted.com>
Date:   Tue Jan 3 13:51:47 2017 -0500

    New and improved

commit f0060fedf04cf334398d1db7ef9655a482221298
Author: Jason Gilliland <redacted@redacted.com>
Date:   Tue Jan 3 13:50:33 2017 -0500

    Started file

-> % git checkout -b branches/default     # to use the branches/* convention
-> % git push origin branches/default
Traceback (most recent call last):
  File "/home/gillilja/bin/git-remote-hg", line 1356, in <module>
    sys.exit(main(sys.argv))
  File "/home/gillilja/bin/git-remote-hg", line 1342, in main
    do_export(parser)
  File "/home/gillilja/bin/git-remote-hg", line 1133, in do_export
    parse_commit(parser)
  File "/home/gillilja/bin/git-remote-hg", line 903, in parse_commit
    node = hghex(repo.commitctx(ctx))
  File "/SFS/product/python/2.7.3/lib/python2.7/site-packages/mercurial/localrepo.py", line 58, in wrapper
    return orig(repo.unfiltered(), *args, **kwargs)
  File "/SFS/product/python/2.7.3/lib/python2.7/site-packages/mercurial/localrepo.py", line 1325, in commitctx
    fctx = ctx[f]
  File "/SFS/product/python/2.7.3/lib/python2.7/site-packages/mercurial/context.py", line 1296, in __getitem__
    return self.filectx(key)
  File "/SFS/product/python/2.7.3/lib/python2.7/site-packages/mercurial/context.py", line 1338, in filectx
    return self._filectxfn(self._repo, self, path)
  File "/home/gillilja/bin/git-remote-hg", line 846, in getfilectx
    is_link, is_exec, rename)
TypeError: __init__() takes at most 6 arguments (7 given)
fatal: Reading from helper 'git-remote-hg' failed
```

I'm able to fix the error, by:
```
-> % git push origin
To hg::/home/gillilja/tmp/remote-hg-test/hg-repo
   f0060fe..4aa00fe  branches/default -> branches/default
   f0060fe..4aa00fe  master -> master
```

But even then:
```
-> % cd ../hg-repo
-> % hg log
changeset:   0:a66abe8db48a
tag:         tip
user:        Jason Gilliland <redacted@redacted.com>
date:        Tue Jan 03 13:50:33 2017 -0500
summary:     Started file

```

The first commit shows up, but not the one I created after cloning.
I'm not sure if I'm missing something about how to actually get my commits onto the remote, or if maybe it's a problem with the fact I'm using a local remote (is that an oxymoron?).

FWIW:
```
-> % git --version
git version 1.8.3.GIT
-> % hg --version
Mercurial Distributed SCM (version 2.8.1)
(see http://mercurial.selenic.com for more information)

Copyright (C) 2005-2013 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by joshuajabbour** [comment]
I'm getting the same types of errors when I try to push back to bitbucket...

**Comment by felipec** [comment]
Actually no, your issue is different, but also fixed.

Please try with the latest version (v0.4). The relevant commit is 5bf7aad6e327dc2e647bd144065d6b770f022482.
