### ISSUE TITLE
Import of "lemon" hg repo failed

### ISSUE THREAD

**Issue by majioa** [felipec/git-remote-hg#83]
Import of "lemon" hg repo failed

```
git clone hg://lemon.cs.elte.hu/hg/lemon/
Cloning into 'lemon'...
Traceback (most recent call last):
  File "/home/majioa/bin/git-remote-hg", line 1400, in <module>
    sys.exit(main(sys.argv))
  File "/home/majioa/bin/git-remote-hg", line 1364, in main
    repo = get_repo(url, alias)
  File "/home/majioa/bin/git-remote-hg", line 418, in get_repo
    repo = hg.repository(myui, url)
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 226, in repository
    createopts=createopts,
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 188, in _peerorrepo
    ui, path, create, intents=intents, createopts=createopts
  File "/usr/lib/python2.7/site-packages/mercurial/localrepo.py", line 3537, in instance
    return makelocalrepository(ui, localpath, intents=intents)
  File "/usr/lib/python2.7/site-packages/mercurial/localrepo.py", line 509, in makelocalrepository
    raise error.RepoError(_(b'repository %s not found') % path)
mercurial.error.RepoError: хранилище hg://lemon.cs.elte.hu/hg/lemon/ не найдено
```

Please fix it.

**Comment by felipec** [comment]
The URL of the repository is `http://lemon.cs.elte.hu/hg/lemon/`, the documentation clearly states that you need to prepend `hg::`, so:

    git clone hg::http://lemon.cs.elte.hu/hg/lemon/
