### ISSUE TITLE
mercurial.error.Abort: stream ended unexpectedly

### ISSUE THREAD

**Issue by psacawa** [felipec/git-remote-hg#88]
Upon running
```
curl https://raw.githubusercontent.com/felipec/git-remote-hg/master/git-remote-hg -o ~/bin/git-remote-hg
chmod +x ~/bin/git-remote-hg
pip install mercurial
```

with versions:
- Python 3.10
- git version 2.25.1
- git-remote-hg 0.6 (a5bc03d)
- Mercurial Distributed SCM (version 6.3.2)
- Python3 mercurial bindings from PyPI version: 6.3.2

I run `git clone hg::https://hg.mozilla.org/mozilla-central/ firefox-source`. It runs for some minutes, with the output:

```
~/git clone hg::https://hg.mozilla.org/mozilla-central/ firefox-source
Klonowanie do „firefox-source”...
applying clone bundle from https://hg.cdn.mozilla.net/mozilla-central/0b74dca33cb0b069ae2c120f72cad1949de685ca.zstd-max.hg
adding changesets
adding manifests
adding file changes
transaction abort!
rollback completed
Traceback (most recent call last):
  File "/usr/local/bin/git-remote-hg", line 1437, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/git-remote-hg", line 1401, in main
    repo = get_repo(url, alias)
  File "/usr/local/bin/git-remote-hg", line 487, in get_repo
    exchange.pull(repo, peer, heads=None, force=True)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/exchange.py", line 1698, in pull
    _maybeapplyclonebundle(pullop)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/exchange.py", line 2813, in _maybeapplyclonebundle
    if trypullbundlefromurl(repo.ui, repo, url):
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/exchange.py", line 2844, in trypullbundlefromurl
    bundle2.applybundle(repo, cg, tr, b'clonebundles', url)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 374, in applybundle
    return processbundle(repo, unbundler, lambda: tr, source=source)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 485, in processbundle
    processparts(repo, op, unbundler)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 491, in processparts
    with partiterator(repo, op, unbundler) as parts:
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 446, in __exit__
    raise exc
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 493, in processparts
    _processpart(op, part)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 567, in _processpart
    handler(op, part)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 2025, in handlechangegroup
    ret = _processchangegroup(
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 497, in _processchangegroup
    ret = cg.apply(op.repo, tr, source, url, **kwargs)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/changegroup.py", line 444, in apply
    newrevs, newfiles = _addchangegroupfiles(
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/changegroup.py", line 1946, in _addchangegroupfiles
    added = fl.addgroup(
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/filelog.py", line 168, in addgroup
    return self._revlog.addgroup(
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/revlog.py", line 2667, in addgroup
    for data in deltas:
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/revlogutils/rewrite.py", line 732, in filter_delta_issue6528
    for rev, d in enumerate(deltas_iter, len(revlog)):
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/changegroup.py", line 586, in deltaiter
    for chunkdata in iter(lambda: self.deltachunk(chain), {}):
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/changegroup.py", line 586, in <lambda>
    for chunkdata in iter(lambda: self.deltachunk(chain), {}):
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/changegroup.py", line 207, in deltachunk
    delta = readexactly(self._stream, l - self.deltaheadersize)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/util.py", line 3164, in readexactly
    s = stream.read(n)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 1460, in read
    data = self._payloadstream.read(size)
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/util.py", line 2703, in read
    for chunk in self.iter:
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/util.py", line 2674, in splitbig
    for chunk in chunks:
  File "/home/psacawa/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mercurial/bundle2.py", line 1319, in decodepayloadchunks
    raise error.Abort(
mercurial.error.Abort: stream ended unexpectedly  (got 5930 bytes, expected 32768)
```

The callstack is deep within the Python bindings. I'm unsure if the error exists with `git-remote-hg` or with upstream mercurial bindings. I will try with other version.

**Comment by psacawa** [comment]
The resolved the issue with `pip install mercurial<6`, which is  version 5.9.3

**Comment by Ismetyt** [comment]
Poli

**Comment by felipec** [comment]
It should work with Mercurial 6, I just tried with 6.3.2 and it works fine. I'm running Python 3.10.9 on Arch Linux.
