### ISSUE TITLE
Git ls-remote error: accessing `persistent-nodemap` repository without associated fast implementation

### ISSUE THREAD

**Issue by amitbhadra** [felipec/git-remote-hg#89]
We have an application where we are trying to fetch this repo: https://foss.heptapod.net/pypy/cffi

What works:
hg clone https://foss.heptapod.net/pypy/cffi 

What doesn't work:
$ git ls-remote hg::https://foss.heptapod.net/pypy/cffi
Traceback (most recent call last):
  File "/bin/git-remote-hg", line 1436, in <module>
    sys.exit(main(sys.argv))
  File "/bin/git-remote-hg", line 1400, in main
    repo = get_repo(url, alias)
  File "/bin/git-remote-hg", line 473, in get_repo
    hg.share(myui, shared_path.encode(), local_path.encode(), update=False)
  File "/build/git/.virtualenv/d/lib64/python3.6/site-packages/mercurial/hg.py", line 303, in share
    srcrepo = repository(ui, source)
  File "/build/git/.virtualenv/d/lib64/python3.6/site-packages/mercurial/hg.py", line 223, in repository
    createopts=createopts,
  File "/build/git/.virtualenv/d/lib64/python3.6/site-packages/mercurial/hg.py", line 185, in _peerorrepo
    ui, path, create, intents=intents, createopts=createopts
  File "/build/git/.virtualenv/d/lib64/python3.6/site-packages/mercurial/localrepo.py", line 3541, in instance
    repo = repo_maker()
  File "/build/git/.virtualenv/d/lib64/python3.6/site-packages/mercurial/localrepo.py", line 3539, in repo_maker
    return makelocalrepository(ui, localpath, intents=intents)
  File "/build/git/.virtualenv/d/lib64/python3.6/site-packages/mercurial/localrepo.py", line 770, in makelocalrepository
    storevfs.options = resolvestorevfsoptions(ui, requirements, features)
  File "/build/git/.virtualenv/d/lib64/python3.6/site-packages/mercurial/localrepo.py", line 1034, in resolvestorevfsoptions
    options.update(resolverevlogstorevfsoptions(ui, requirements, features))
  File "/build/git/.virtualenv/d/lib64/python3.6/site-packages/mercurial/localrepo.py", line 1178, in resolverevlogstorevfsoptions
    raise error.Abort(msg, hint=hint)
mercurial.error.Abort: accessing `persistent-nodemap` repository without associated fast implementation.

I do see a few recommendations like 'use-persistent-nodemap' in https://manpages.debian.org/testing/mercurial-common/hgrc.5.en.html#use, but is there a way to fix this in the script?

**Comment by felipec** [comment]
I don't know what you are trying to do, that command works fine here, however, this is how you are supposed to do it:

    git clone hg::https://foss.heptapod.net/pypy/cffi
    git ls-remote origin
